api/urls.py
from django.conf.urls import url
from django.contrib import admin
import views


urlpatterns = [
    url(r'^building/$', views.retrieve_all, name='buildings_list'),
    url(r'^building/(?P<building_id>\d+)$', views.retrieve, name='building_one'),
    url(r'^building/filter/$', views.retrieve_by_params, name='building_filter'),
    url(r'^booking/$', views.create_booking, name='booking_create'),
]

buildings/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^admin/', admin.site.urls),
]

api/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils.timezone import now
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.db import models

# Create your models here.


class City(models.Model):
    name = models.CharField(max_length=50)

    def __unicode__(self):
        return self.name


private_storage = FileSystemStorage(location=settings.PRIVATE_STORAGE_ROOT)


class Building(models.Model):
    title = models.CharField(max_length=50)
    facilities = models.TextField(max_length=500)
    services = models.TextField(max_length=500)
    cant_pax = models.PositiveSmallIntegerField()
    stars = models.PositiveSmallIntegerField(default=1)
    daily_cost = models.FloatField()
    image = models.ImageField(storage=private_storage)
    city = models.ForeignKey(City, on_delete=models.CASCADE)

    def __unicode__(self):
        return self.title


class Booking(models.Model):
    building = models.ForeignKey(Building, on_delete=models.CASCADE)
    total_cost = models.FloatField()

    def __unicode__(self):
        return str(self.pk) + ' - ' + self.building.__str__()


class BookingDate(models.Model):
    date = models.DateField(auto_now=False, default=now)
    building = models.ForeignKey(Building, on_delete=models.CASCADE)
    booking = models.ForeignKey(Booking, on_delete=models.CASCADE, default=None, null=True, blank=True)

    def __unicode__(self):
        return self.date.__str__() + ' - ' + self.building.__str__()

api/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from .models import (
    City,
    Building,
    Booking,
    BookingDate
)
from django.shortcuts import render, redirect

# Create your views here.


def building_mapper(building):
    building.stars = range(building.stars)
    return building


def retrieve_all(request):
    buildings = map(building_mapper,Building.objects.all())
    return render(request, 'buildings_list.html', {'buildings': buildings})


def retrieve(request, building_id):
    building = building_mapper(Building.objects.get(pk=building_id))
    dates = BookingDate.objects.filter(building=building.pk, booking=None)

    return render(request, 'building_one.html', {'building': building, 'dates': dates, 'cant_pax': range(1, building.cant_pax)})


def retrieve_by_params(request):
    if request.method == "POST":
        city_name = request.POST.get("city_name")
        begin_date = request.POST.get("begin_date")
        end_date = request.POST.get("end_date")

        if begin_date and end_date:
            booking_dates = BookingDate.objects.filter(date__range=(begin_date, end_date))
        else:
            booking_dates = BookingDate.objects.all()

        buildings = []
        flag = 1
        for booking_date in booking_dates:
            for building in buildings:
                if building.pk == booking_date.building.pk:
                    flag = 0
                    break
            if flag == 1:
                buildings.append(booking_date.building)
            else:
                flag = 1
        buildings = map(building_mapper, buildings)

        if city_name:
            buildings = filter(lambda obj: obj.city.name == city_name, buildings)
    else:
        buildings = map(building_mapper, Building.objects.all())

    return render(request, "buildings_list.html", {'buildings': buildings})


def create_booking(request):
    if request.method == "POST":
        building_id = request.POST.get("building_id")
        cant_pax = request.POST.get("cant_pax")
        dates_pk = dict(request.POST)["dates"]

        building = Building.objects.get(pk=building_id)

        booking = Booking()
        booking.building = building
        booking.total_cost = building.daily_cost * float(cant_pax)
        booking.save()

        for date_pk in dates_pk:
            booking_date = BookingDate.objects.get(pk=date_pk)
            booking_date.booking = booking
            booking_date.save(force_update=True)

    return redirect('/api/building/')

api/templates/building_one.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Tribooking</title>
    <meta name="description" content="Sitio web de booking super especial">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% load static %}
    <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.png' %}">
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
        crossorigin="anonymous">
</head>

<body id="bookingPage">
    <header>
        <!-- Just an image -->
        <nav class="navbar navbar-light " id="theNav">
            <a class="navbar-brand" href="{% url 'api:buildings_list' %}">
                <img src="{% static 'img/favicon.png' %}" width="50" height="50" alt=""> Tribooking
            </a>
        </nav>
    </header>
    <div class="mt-5">
        <!--  margin-top to $spacer * 3 -->
    </div>
    <main class="container">
        <div class="row">
            <div class="col-sm-5">

                <form action="{% url 'api:booking_create' %}" method="POST">

                    <input type="hidden" value="{{ building.pk }}" name="building_id">

                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label for="name">Nombre</label>
                            <input type="text" class="form-control" id="name" placeholder="Nombre" required>
                        </div>
                        <div class="form-group col-md-6">
                            <label for="surname">Apellido</label>
                            <input type="text" class="form-control" id="surname" placeholder="Apellido" required>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="email">Email</label>
                        <input type="email" class="form-control" id="email" placeholder="Ingresa un email" required>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-12">
                            <label for="dates">Dias (Manten presionado CTRL y clickea)</label>
                            <select name="dates" id="dates" class="form-control" multiple="multiple" required>
                                {% for date in dates %}
                                    <option value="{{ date.pk }}">{{ date.date }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6">
                            <label for="number_card">Tarjeta de Credito</label>
                            <input type="text" class="form-control" id="number_card" placeholder="xxxx-xxxx-xxxx-xxxx" required>
                        </div>
                        <div class="form-group col-md-4">
                            <label for="cvv">CVV</label>
                            <input type="text" class="form-control" id="cvv" placeholder="xxx" required>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-4">
                            <label for="pax">Personas</label>
                            <select name="cant_pax" class="form-control" id="pax" required>
                                {% for pax in cant_pax %}
                                    <option value="{{ pax }}">{{ pax }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>

                    <button type="submit" class="btn btn-success">Reservar</button>
                </form>
            </div>
            <div class="px-2">
                <!--  padding set both *-top and *-bottom to $spacer * 0.5 -->
            </div>
            <div class="col-sm-5">
                <div class="card" style="width: 45rem;">
                    <img class="img-fluid" src="https://static.grandvoyage.com/img/overwater_private_villa_en_maldivas-790x395.jpg">
                    <div class="card-body">
                        <h5 class="card-title"> {{ building.title }}, {{ building.city.name }} </h5>
                        <p class="card-text"> {{ building.facilities }} </p>
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item"> {{ building.services }} </li>
                    </ul>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item"> $ {{ building.daily_cost }} / Noche </li>
                    </ul>
                </div>
            </div>
        </div>
    </main>
    <!--Scripts-->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
</body>

</html>

api/templates/buildings_list.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Tribooking</title>

  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css" integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns"
    crossorigin="anonymous">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!--<link rel="stylesheet" type="text/css" media="screen" href="./css/main.css" />-->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
    crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-rc.19/css/uikit.min.css" />
  <style>
    #theNav{
/* Permalink - use to edit and share this gradient: http://colorzilla.com/gradient-editor/#b8e1fc+0,a9d2f3+10,90bcea+37,90bff0+39,a2daf5+69,6ba8e5+88,6ba8e5+100,bdf3fd+100 */
background: rgb(184,225,252); /* Old browsers */
background: -moz-linear-gradient(top, rgb(184,225,252) 0%, rgb(169,210,243) 10%, rgb(144,188,234) 37%, rgb(144,191,240) 39%, rgb(162,218,245) 69%, rgb(107,168,229) 88%, rgb(107,168,229) 100%, rgb(189,243,253) 100%); /* FF3.6-15 */
background: -webkit-linear-gradient(top, rgb(184,225,252) 0%,rgb(169,210,243) 10%,rgb(144,188,234) 37%,rgb(144,191,240) 39%,rgb(162,218,245) 69%,rgb(107,168,229) 88%,rgb(107,168,229) 100%,rgb(189,243,253) 100%); /* Chrome10-25,Safari5.1-6 */
background: linear-gradient(to bottom, rgb(184,225,252) 0%,rgb(169,210,243) 10%,rgb(144,188,234) 37%,rgb(144,191,240) 39%,rgb(162,218,245) 69%,rgb(107,168,229) 88%,rgb(107,168,229) 100%,rgb(189,243,253) 100%); /* W3C, IE10+, FF16+, Chrome26+, Opera12+, Safari7+ */
filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#b8e1fc', endColorstr='#bdf3fd',GradientType=0 ); /* IE6-9 */
}
@import url(https://fonts.googleapis.com/css?family=Lato:400,700,900);


*, *:before, *:after {
  box-sizing: border-box;
}

body {
    background: rgb(184,225,252); /* Old browsers */
background: -moz-linear-gradient(top, rgb(184,225,252) 0%, rgb(169,210,243) 10%, rgb(144,188,234) 37%, rgb(144,191,240) 39%, rgb(162,218,245) 69%, rgb(107,168,229) 88%, rgb(107,168,229) 100%, rgb(189,243,253) 100%); /* FF3.6-15 */
background: -webkit-linear-gradient(top, rgb(184,225,252) 0%,rgb(169,210,243) 10%,rgb(144,188,234) 37%,rgb(144,191,240) 39%,rgb(162,218,245) 69%,rgb(107,168,229) 88%,rgb(107,168,229) 100%,rgb(189,243,253) 100%); /* Chrome10-25,Safari5.1-6 */
background: linear-gradient(to bottom, rgb(184,225,252) 0%,rgb(169,210,243) 10%,rgb(144,188,234) 37%,rgb(144,191,240) 39%,rgb(162,218,245) 69%,rgb(107,168,229) 88%,rgb(107,168,229) 100%,rgb(189,243,253) 100%); /* W3C, IE10+, FF16+, Chrome26+, Opera12+, Safari7+ */
filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#b8e1fc', endColorstr='#bdf3fd',GradientType=0 ); /* IE6-9 */
  background-size: cover;
  font: 14px/20px "Lato", Arial, sans-serif;
  color: #9E9E9E;

}

.slide-container {
  margin: 0 auto;
  width: 600px;
  text-align: center;
}

.wrapper {
    padding-top:40px;
  padding-bottom: 40px;
}
 .wrapper:focus {
    outline: 0;
  }




.clash-card {
  background: white;
  width: 300px;
  display: inline-block;
  margin: auto;
  position: relative;
  text-align: center;
  box-shadow: -1px 15px 30px -12px black;
  z-index: 9999;
}

.clash-card__image {
  position: relative;
  margin-bottom: 35px;
  border-top-left-radius: 14px;
  border-top-right-radius: 14px;
}



.clash-card__level {
  text-transform: uppercase;
  font-size: 12px;
  font-weight: 700;
  margin-bottom: 3px;
}

.clash-card__level--barbarian {
  color: #EC9B3B;
}

.clash-card__level--archer {
  color: #EE5487;
}

.clash-card__level--giant {
  color: #F6901A;
}

.clash-card__level--goblin {
  color: #82BB30;
}

.clash-card__level--wizard {
  color: #4FACFF;
}

.clash-card__unit-name {
  font-size: 26px;
  color: black;
  font-weight: 900;
  margin-bottom: 5px;
}

.clash-card__unit-description {
  padding: 20px;
  margin-bottom: 10px;
}

.clash-card__unit-stats--barbarian {
  background: rgb(166, 145, 80);
  }

  .one-third {
     border-right: 1px solid rgb(207, 204, 198);
  }
  .one-two {
     border-right: 1px solid rgb(207, 204, 198);
  }




.clash-card__unit-stats {

  color: white;
  font-weight: 700;

}
  .one-third {
    width: 33%;
    float: left;
    padding: 20px 15px;
  }
  .one-two {
    width: 50%;
    float: left;
    padding: 20px 15px;
  }

  sup {
    position: absolute;
    bottom: 4px;
    font-size: 45%;
    margin-left: 2px;
  }

  .stat {
    position: relative;
    font-size: 24px;
    margin-bottom: 10px;
  }

  .stat-value {
    text-transform: uppercase;
    font-weight: 400;
    font-size: 12px;
  }

  .no-border {
    border-right: none;
  }


.clearfix:after {
	visibility: hidden;
	display: block;
	font-size: 0;
	content: " ";
	clear: both;
	height: 0;
}

.slick-prev {
  left: 100px;
  z-index: 999;
}

.slick-next {
  right: 100px;
  z-index: 999;
}
.hint-star {
	display: inline-block;
	margin-left: 0.5em;
	color: gold;
	width: 50%;
}
h3{
    font-family:'Trebuchet MS', 'Lucida Sans Unicode', 'Lucida Grande', 'Lucida Sans', Arial, sans-serif;
}
</style>
</head>

<body>
  <nav class="navbar navbar-light" id="theNav">
    <a class="navbar-brand" href="{% url 'api:buildings_list' %}">
      {% load static %}
      <img src="{% static 'img/favicon.png' %}" width="50" height="50" alt="">
      Tribooking
    </a>
  </nav>
  </div>
  <main class="container-fluid">

    <section class="row" style="background-image:url({% static 'img/fondo03.jpg' %}); background-repeat: no-repeat; background-size: cover; height: 90vh;">
      <section class="col-md-6 mt-5 ml-5">
        <div class="card" style="width:400px;height:400px; background-color:white; box-shadow: 0 0 15px 10px rgba(0,0,0,.6);">

          <div class="card-header text-center" style="color:black;">
            Busca tu Alojamiento en Tribooking
          </div>
          <div class="card-body row">

            <form class="mt-2" action="{% url 'api:building_filter' %}" method="POST">
              <div class="form-row mt-2">
                <div class="form-group col-md-12">
                  <label for="input-donde">Nombre de la ciudad</label>
                  <input type="text" name="city_name" class="form-control" id="input-donde" placeholder="Donde quieres ir">
                </div>
              </div>
              <div class="form-row mt-4">
                <div class="form-group col-md-6">
                  <label for="input_from">Llegada</label>
                  <input type="date" name="begin_date" class="form-control" id="input_from">
                </div>
                <div class="form-group col-md-6">
                  <label for="input_to">Salida</label>
                  <input type="date" name="end_date" class="form-control" id="input_to">
                </div>
              </div>
              <button type="submit" class="btn btn-danger col-md-12 mt-4">Buscar</button>
            </form>
          </div>
        </div>
      </section>
    </section>
    <section class="row mt-5">
      <section class="container">
        <div class="row">
          <div class="col-md-4">
            <div class="card  bg-success">
              <div class="card-header"> <span><i class="fas fa-map-marked-alt ml-5"><i class="ml-5">Sentimientos</i></i></i></span></div>
            </div>
          </div>
          <div class="col-md-4">
            <div class="card bg-warning">
              <div class="card-header"><span><i class="fas fa-hotel ml-5"><i class="ml-5">Lujos</i></i></span></div>
            </div>

          </div>
          <div class="col-md-4">
            <div class="card bg-info">
              <div class="card-header"><span><i class="fas fa-globe-americas ml-5"><i class="ml-5">Experiencias</i></i></i></span></div>
            </div>
          </div>
        </div>
        <section class="">
          <div class="row slider-container">

            {% for building in buildings %}
            <a class="navbar-brand" href="{% url 'api:building_one' building.pk %}">
              <div class="col-md-4 wrapper ">
                <div class="clash-card barbarian">
                  <div class="clash-card__image clash-card__image--barbarian">
                    <img src="{% static 'building_images/' %}{{building.image}}" class="barbarianImg" alt="Imagen propiedad" />
                  </div>
                  <div class="clash-card__level clash-card__level--barbarian">
                    <span class="hint-star star">
                      {% for star in building.stars %}
                      <i class="fa fa-star" aria-hidden="true"></i>
                      {% endfor %}
                    </span>
                  </div>
                  <div class="clash-card__unit-name">{{ building.title }}</div>
                  <div class="clash-card__unit-description">
                    {{ building.facilities }}
                  </div>
                  <div class="clash-card__unit-stats clash-card__unit-stats--barbarian clearfix">
                    <div class="one-two">
                      <div class="stat">{{ building.cant_pax }}</div>
                      <div class="stat-value">Pasajeros</div>
                    </div>
                    <div class="one-two no-border">
                      <div class="stat">$ {{ building.daily_cost }} </div>
                      <div class="stat-value">$/noche</div>
                    </div>
                  </div>
                </div> <!-- end clash-card barbarian-->
              </div> <!-- end wrapper -->
            </a>
          {% endfor %}
          </div>
        </section>
      </section>
    </section>
  </main>
</body>
<script>

  $(document).ready(function () {
    var zindex = 10;

    $("div.card").click(function (e) {
      e.preventDefault();

      var isShowing = false;

      if ($(this).hasClass("show")) {
        isShowing = true
      }

      if ($("div.cards").hasClass("showing")) {
        // a card is already in view
        $("div.card.show")
          .removeClass("show");

        if (isShowing) {
          // this card was showing - reset the grid
          $("div.cards")
            .removeClass("showing");
        } else {
          // this card isn't showing - get in with it
          $(this)
            .css({ zIndex: zindex })
            .addClass("show");

        }

        zindex++;

      } else {
        // no cards in view
        $("div.cards")
          .addClass("showing");
        $(this)
          .css({ zIndex: zindex })
          .addClass("show");

        zindex++;
      }

    });
  });</script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
  crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
  crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
  crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-rc.19/js/uikit.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-rc.19/js/uikit-icons.min.js"></script>

</html>